Print uploaded files in verbose mode
ios-control/ios-deploy pull request #520
Opened 2021-06-11 09:50 UTC by eunikolsky

This logs the uploaded directories and files in the verbose mode (`-v`)
similar to logging the downloaded directories and files (however that
doesn't require the verbose mode).

Fixes #519.

For example:
```bash
$ ./ios-deploy -v -1 io.realm.Simple --upload=$HOME/Desktop/simple --to=/
[....] Waiting for iOS device to be connected
Handling device type: 1
Already found device? 0
Hardware Model: J72bAP
Device Name: iPadw
Model Name: iPad (2018)
SDK Name: iphoneos
Architecture Name: arm64
Product Version: 14.4.1
Build Version: 18D61
[....] Using X (J72bAP, iPad (2018), iphoneos, arm64, 14.4.1, 18D61) a.k.a. 'iPad'.
/Library/
/Library/Saved Application State/
/Library/Saved Application State/io.realm.Simple.savedState/
/Library/Saved Application State/io.realm.Simple.savedState/KnownSceneSessions/
/Library/Saved Application State/io.realm.Simple.savedState/KnownSceneSessions/data.data
/Library/Preferences/
/Library/SplashBoard/
/Library/SplashBoard/Snapshots/
/Library/SplashBoard/Snapshots/io.realm.Simple - {DEFAULT GROUP}/
/Library/SplashBoard/Snapshots/io.realm.Simple - {DEFAULT GROUP}/9B15514B-5DCB-4A37-8F2A-33A23A9451A7@2x.ktx
/Library/SplashBoard/Snapshots/io.realm.Simple - {DEFAULT GROUP}/downscaled/
/Library/SplashBoard/Snapshots/io.realm.Simple - {DEFAULT GROUP}/downscaled/86A9F37C-EB1B-41BD-B352-B0F85280179B@2x.ktx
/Library/Caches/
/Library/Caches/io.realm.Simple/
/Library/Caches/io.realm.Simple/Cache.db-shm
/Library/Caches/io.realm.Simple/com.apple.metalfe/
/Library/Caches/io.realm.Simple/Cache.db-wal
/Library/Caches/io.realm.Simple/Cache.db
/Documents/
/Documents/default.realm.management/
/Documents/default.realm.management/access_control.write.mx
/Documents/default.realm.management/access_control.control.mx
/Documents/default.realm
/Documents/default.realm.lock
/tmp/
```

2021-06-11 13:26 UTC, gabebear requested changes
This seems like it would log nothing it you uploaded a single file
```
upload_file() -> upload_single_file()
```
that case bypasses upload_dir()

2021-06-11 15:06 UTC, eunikolsky commented
@gabebear, thanks for the comment! I've updated the commit by moving one of the logs line into `upload_single_file()`.

2021-06-11 15:12 UTC, gabebear commented
> @gabebear, thanks for the comment! I've updated the commit by moving one of the logs line into `upload_single_file()`.

That seems correct now.

Could you also add another log to each verbose log statement so we get output when someone specifies `--json`. Something like:
```
NSLogJSON(@{@"Event": @"UploadFile",
            @"Destination": destinationPath
            });
```

2021-06-12 06:33 UTC, eunikolsky commented
@gabebear, added logging to JSON. It looks like this:
```json
{
  "Event" : "UploadDir",
  "Destination" : "\/Library\/"
}{
  "Event" : "UploadDir",
  "Destination" : "\/Library\/Saved Application State\/"
}{
  "Event" : "UploadDir",
  "Destination" : "\/Library\/Saved Application State\/io.realm.Simple.savedState\/"
}{
  "Event" : "UploadDir",
  "Destination" : "\/Library\/Saved Application State\/io.realm.Simple.savedState\/KnownSceneSessions\/"
}{
  "Event" : "UploadFile",
  "Destination" : "\/Library\/Saved Application State\/io.realm.Simple.savedState\/KnownSceneSessions\/data.data"
}
```

2021-07-19 13:21 UTC, gabebear approved these changes

2021-07-19 13:21 UTC, merged